name: C/C++ Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up C++ environment
      uses: actions/setup-cpp@v2
      with:
        compiler: 'g++-10'  # Use the appropriate compiler version

    - name: Compile and run C++ code
      run: |
        g++ -o Movie_Rental_And_Buying_System DiverCode.cpp
        if [ $? -eq 0 ]; then
          ./Movie_Rental_And_Buying_System
        else
          echo "Compilation failed."
        fi
